import React, { useMemo, useState } from 'react';
import { CheckCircle2, CheckSquare, FolderOpen, Loader2, ShieldCheck, Square, Trash2, X } from 'lucide-react';
import { DeviceStorageFile, StorageSource, DriveFile, FileCategory } from '../types';
import { MOCK_DEVICE_FILES } from '../lib/deviceStorageMock';
import { formatBytes } from '../lib/driveApi';

type DirHandle = { kind:'directory'; name:string; entries():AsyncIterableIterator<[string, FileHandle|DirHandle]>; getDirectoryHandle(name:string, options?:{create?:boolean}):Promise<DirHandle>; getFileHandle(name:string, options?:{create?:boolean}):Promise<FileHandle>; removeEntry(name:string, options?:{recursive?:boolean}):Promise<void>; queryPermission?:(o?:{mode?:'read'|'readwrite'})=>Promise<PermissionState>; requestPermission?:(o?:{mode?:'read'|'readwrite'})=>Promise<PermissionState>; };
type FileHandle = { kind:'file'; name:string; getFile():Promise<File>; queryPermission?:(o?:{mode?:'read'|'readwrite'})=>Promise<PermissionState>; requestPermission?:(o?:{mode?:'read'|'readwrite'})=>Promise<PermissionState>; createWritable():Promise<{write(data:Blob|ArrayBuffer|string):Promise<void>;close():Promise<void>}>; };
type PickedEntry = { id:string; name:string; path:string; source:StorageSource; size:number; modifiedTime:string; mimeType:string; category:FileCategory; fingerprint:string; fileHandle?:FileHandle; parentHandle?:DirHandle; isDuplicate:boolean; };
type PickerWindow = Window & { showDirectoryPicker?: (o?:{id?:string;mode?:'read'|'readwrite'})=>Promise<DirHandle> };

async function permission(handle:DirHandle|FileHandle, mode:'read'|'readwrite'):Promise<boolean>{ if(handle.queryPermission && await handle.queryPermission({mode})==='granted') return true; if(handle.requestPermission) return await handle.requestPermission({mode})==='granted'; return true; }
async function fingerprint(file:File):Promise<string>{ const size=file.size, chunk=64*1024; const first=await file.slice(0,Math.min(chunk,size)).arrayBuffer(); const last=size>chunk?await file.slice(Math.max(0,size-chunk),size).arrayBuffer():first; const bytes=new Uint8Array(first.byteLength+last.byteLength); bytes.set(new Uint8Array(first)); bytes.set(new Uint8Array(last),first.byteLength); const digest=await crypto.subtle.digest('SHA-256',bytes); return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')+':'+size; }
async function scanDirectory(root:DirHandle,source:StorageSource):Promise<PickedEntry[]>{ const out:PickedEntry[]=[]; const walk=async(dir:DirHandle,prefix:string)=>{ for await(const [name,entry] of dir.entries()){ if(name.startsWith('.')||name==='Duplicates-Review') continue; if(entry.kind==='directory'){await walk(entry,prefix?prefix+'/'+name:name);continue;} const file=await entry.getFile(); const category:FileCategory=file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':file.type.includes('sheet')||/\.(csv|xls|xlsx)$/i.test(name)?'spreadsheet':file.type.includes('pdf')||/\.(pdf|doc|docx|txt|rtf)$/i.test(name)?'document':/\.(zip|rar|7z)$/i.test(name)?'archive':'other'; out.push({id:source+':'+(prefix?prefix+'/':'')+name,name,path:prefix?prefix+'/'+name:name,source,size:file.size,modifiedTime:new Date(file.lastModified).toISOString(),mimeType:file.type||'application/octet-stream',category,fingerprint:await fingerprint(file),fileHandle:entry,parentHandle:dir,isDuplicate:false}); }}; await walk(root,''); return out; }

interface Props { onImportToDrive:(file:DriveFile)=>void; onSelectPreviewFile?:(file:DriveFile)=>void; }
export const DeviceStorageScanner:React.FC<Props>=({onImportToDrive,onSelectPreviewFile})=>{
 const [files,setFiles]=useState<PickedEntry[]>(MOCK_DEVICE_FILES.map(f=>({id:f.id,name:f.name,path:f.path,source:f.source,size:f.size,modifiedTime:f.lastModified,mimeType:f.mimeType,category:f.category,fingerprint:'demo:'+f.size+':'+f.name.toLowerCase(),isDuplicate:Boolean(f.isDuplicate)})));
 const [roots,setRoots]=useState<Partial<Record<StorageSource,DirHandle>>>({}),[selected,setSelected]=useState<Set<string>>(new Set()),[source,setSource]=useState<'all'|StorageSource>('all'),[query,setQuery]=useState(''),[scanning,setScanning]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[moveName,setMoveName]=useState('Duplicates-Review'),[confirm,setConfirm]=useState<'move'|'delete'|null>(null);
 const show=(m:string)=>{setMessage(m);window.setTimeout(()=>setMessage(null),4000);};
 const duplicates=useMemo(()=>{const map=new Map<string,PickedEntry[]>();for(const f of files){const a=map.get(f.fingerprint)||[];a.push(f);map.set(f.fingerprint,a);}const ids=new Set<string>();for(const g of map.values())if(g.length>1)g.slice(1).forEach(f=>ids.add(f.id));return ids;},[files]);
 const visible=useMemo(()=>files.filter(f=>(source==='all'||f.source===source)&&(!query.trim()||(f.name+' '+f.path).toLowerCase().includes(query.toLowerCase().trim()))).map(f=>({...f,isDuplicate:duplicates.has(f.id)})),[files,source,query,duplicates]);
 const selectRoot=async(which:StorageSource)=>{const picker=(window as PickerWindow).showDirectoryPicker;if(!picker){show('इस browser में folder write access उपलब्ध नहीं है। Chrome Android में HTTPS पर app खोलें।');return;}try{const root=await picker({id:which,mode:'readwrite'});if(!(await permission(root,'readwrite'))){show('Write permission नहीं मिली; कोई बदलाव नहीं किया गया।');return;}setRoots(p=>({...p,[which]:root}));setScanning(true);const scanned=await scanDirectory(root,which);setFiles(p=>[...p.filter(f=>f.source!==which),...scanned]);setSelected(new Set());setScanning(false);show((which==='phone_internal'?'Phone storage':'SD card')+': '+scanned.length+' files indexed. Nothing was moved or deleted.');}catch(e){setScanning(false);if((e as DOMException)?.name!=='AbortError')show('Storage scan failed: '+(e instanceof Error?e.message:'permission denied'));}};
 const asDriveFile=(f:PickedEntry):DriveFile=>({id:'device-preview-'+f.id,name:f.name,mimeType:f.mimeType,size:f.size,modifiedTime:f.modifiedTime,createdTime:f.modifiedTime,category:f.category,isOffline:false,isEncrypted:false,contentHash:'device-'+f.fingerprint,tags:[f.source,f.category,'device-picker'],semanticSummary:'Selected local file: '+f.path,starred:false});
 const selectedEntries=visible.filter(f=>selected.has(f.id)), duplicateSelected=selectedEntries.filter(f=>f.isDuplicate);
 const moveSelected=async()=>{setConfirm(null);setBusy(true);try{const byRoot=new Map<StorageSource,PickedEntry[]>();for(const f of duplicateSelected){const a=byRoot.get(f.source)||[];a.push(f);byRoot.set(f.source,a);}let moved=0;for(const [src,list] of byRoot){const root=roots[src];if(!root||!(await permission(root,'readwrite')))continue;const target=await root.getDirectoryHandle(moveName.trim()||'Duplicates-Review',{create:true});for(const f of list){if(!f.fileHandle||!f.parentHandle)continue;const file=await f.fileHandle.getFile();const ext=f.name.includes('.')?f.name.slice(f.name.lastIndexOf('.')):'';const stem=ext?f.name.slice(0,-ext.length):f.name;let targetName=f.name;let suffix=1;while(true){try{await target.getFileHandle(targetName);targetName=stem+' (duplicate '+suffix+')'+ext;suffix++;}catch{break;}}const out=await target.getFileHandle(targetName,{create:true});const writable=await out.createWritable();await writable.write(file);await writable.close();await f.parentHandle.removeEntry(f.name);moved++;}}setFiles(p=>p.filter(f=>!duplicateSelected.some(d=>d.id===f.id)));setSelected(new Set());show(moved+' duplicate files moved to "'+(moveName.trim()||'Duplicates-Review')+'". Source was removed only after successful copy.');}catch(e){show('Move stopped safely: '+(e instanceof Error?e.message:'unknown error'));}finally{setBusy(false);}};
 const deleteSelected=async()=>{setConfirm(null);setBusy(true);try{let deleted=0;for(const f of duplicateSelected){if(!f.parentHandle||!f.fileHandle)continue;const root=roots[f.source];if(!root||!(await permission(root,'readwrite')))continue;await f.parentHandle.removeEntry(f.name);deleted++;}setFiles(p=>p.filter(f=>!duplicateSelected.some(d=>d.id===f.id)));setSelected(new Set());show(deleted+' files deleted after your explicit confirmation.');}catch(e){show('Delete stopped; remaining files were not touched: '+(e instanceof Error?e.message:'unknown error'));}finally{setBusy(false);}};
 const toggle=(id:string)=>setSelected(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});
 return <div className="space-y-5">{message&&<div className="fixed top-20 right-4 z-50 rounded-xl bg-zinc-900 text-white px-4 py-3 text-xs shadow-xl flex gap-2 items-center"><CheckCircle2 className="w-4 h-4 text-emerald-400"/><span>{message}</span><button onClick={()=>setMessage(null)}><X className="w-4 h-4"/></button></div>}
 <section className="rounded-2xl border border-amber-200 bg-amber-50 dark:bg-amber-950/20 p-4 space-y-3"><div className="flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-amber-600 shrink-0"/><div><h2 className="font-bold">Safe Storage Cleaner</h2><p className="text-xs text-zinc-600 dark:text-zinc-400">यह app अपने-आप कोई local file delete नहीं करता। पहले folder access की अनुमति, फिर आपकी दूसरी पुष्टि आवश्यक है। Move में पहले copy पूरा होता है, उसके बाद ही source हटता है।</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>selectRoot('phone_internal')} disabled={scanning||busy} className="px-3 py-2 rounded-xl bg-blue-600 text-white text-xs font-bold inline-flex gap-1.5 items-center"><FolderOpen className="w-4 h-4"/> Phone storage चुनें</button><button type="button" onClick={()=>selectRoot('sd_card')} disabled={scanning||busy} className="px-3 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold inline-flex gap-1.5 items-center"><FolderOpen className="w-4 h-4"/> SD card चुनें</button></div><p className="text-[11px] text-zinc-500">Picker में Phone की internal storage या SD card का root/वांछित folder स्वयं चुनें। Web app Android की पूरी storage को बिना आपकी अनुमति scan नहीं कर सकती।</p></section>
 <div className="flex flex-wrap gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="फ़ाइल नाम खोजें..." className="flex-1 min-w-[160px] px-3 py-2 rounded-xl border text-sm"/><select value={source} onChange={e=>setSource(e.target.value as 'all'|StorageSource)} className="px-3 py-2 rounded-xl border text-xs"><option value="all">Phone + SD</option><option value="phone_internal">Phone</option><option value="sd_card">SD</option></select><button type="button" onClick={()=>setSelected(new Set(visible.filter(f=>f.isDuplicate).map(f=>f.id)))} className="px-3 py-2 rounded-xl border text-xs font-semibold">Select duplicates</button></div>
 <div className="flex flex-wrap items-center gap-2 text-xs"><span className="font-semibold">{visible.length} files • {visible.filter(f=>f.isDuplicate).length} duplicate candidates • {duplicateSelected.length} selected</span>{duplicateSelected.length>0&&<><input value={moveName} onChange={e=>setMoveName(e.target.value)} className="w-40 px-2 py-1.5 rounded-lg border" aria-label="new folder name"/><button type="button" disabled={busy} onClick={()=>setConfirm('move')} className="px-3 py-1.5 rounded-lg bg-emerald-600 text-white font-bold">Move selected to new folder</button><button type="button" disabled={busy} onClick={()=>setConfirm('delete')} className="px-3 py-1.5 rounded-lg border border-red-300 text-red-600 font-bold"><Trash2 className="inline w-3.5 h-3.5 mr-1"/>Delete selected</button></>}</div>
 {scanning&&<div className="flex items-center gap-2 text-xs text-blue-600"><Loader2 className="w-4 h-4 animate-spin"/>Storage scan चल रहा है…</div>}
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{visible.slice(0,500).map(f=><div key={f.id} className="rounded-xl border p-3 bg-white dark:bg-zinc-900 flex items-start gap-2"><button type="button" onClick={()=>toggle(f.id)}>{selected.has(f.id)?<CheckSquare className="w-4 h-4 text-blue-600"/>:<Square className="w-4 h-4 text-zinc-400"/>}</button><div className="min-w-0 flex-1"><div className="text-sm font-semibold truncate">{f.name}</div><div className="text-[10px] text-zinc-500">{formatBytes(f.size)} • {f.source==='sd_card'?'SD':'Phone'} • {f.path}</div>{f.isDuplicate&&<span className="text-[10px] text-amber-700 font-bold">Duplicate candidate</span>}</div>{onSelectPreviewFile&&<button type="button" onClick={()=>onSelectPreviewFile(asDriveFile(f))} className="px-2 py-1 rounded-lg border text-[10px]">Details</button>}</div>)}</div>
 {visible.length>500&&<p className="text-center text-xs text-zinc-500">Showing first 500.</p>}{visible.length===0&&<p className="text-center py-8 text-sm text-zinc-500">पहले Phone storage या SD card चुनें।</p>}
 {confirm&&<div className="fixed inset-0 z-[70] bg-black/60 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl bg-white dark:bg-zinc-900 p-5 space-y-4 shadow-2xl"><h3 className="font-bold">{confirm==='move'?'Move की अंतिम अनुमति':'Delete की अंतिम अनुमति'}</h3><p className="text-sm">आप {duplicateSelected.length} duplicate candidate files पर {confirm==='move'?'Move':'Delete'} करने वाले हैं। {confirm==='move'?'पहले नए folder में copy होगी; सफल copy के बाद source हटेगा।':'यह local filesystem से वास्तविक deletion करेगा।'}</p><div className="flex justify-end gap-2"><button type="button" onClick={()=>setConfirm(null)} className="px-3 py-2 rounded-lg border">Cancel</button><button type="button" onClick={confirm==='move'?moveSelected:deleteSelected} className="px-3 py-2 rounded-lg bg-red-600 text-white font-bold">{confirm==='move'?'हाँ, Move करें':'हाँ, Delete करें'}</button></div></div></div>}</div>;
};